theme: jekyll-theme-minimal
logo: https://miro.medium.com/max/494/1*DR1v-Np-HyduhCASpB7XcQ.png
logo: https://etaluma.com/wp-content/uploads/2015/09/ucsd-logo.jpg

title: Robertha's Bioinformatics Projects (BIMM143 SP19)

 
