theme: jekyll-theme-minimal
title:Robertha's Bioinformatics (BIMM SP19)
logo: https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwierfbAtdDiAhVWvZ4KHXzMBLYQjRx6BAgBEAU&url=https%3A%2F%2Ftowardsdatascience.com%2Fwhat-is-bioinformatics-703170763999&psig=AOvVaw3zPRTZcOEtLia9K1o9wMtW&ust=1559757966044885
