theme: jekyll-theme-minimal
logo: https://miro.medium.com/max/494/1*DR1v-Np-HyduhCASpB7XcQ.png
title: Robertha's Bioinformatics Projects (BIMM143 SP19)

Robertha Diaz Amezola
University of California,San Diego
B.S Biochemistry and Cellular Biology
Minor Global Health


contact
ramezola@ucsd.edu
roberthaamezola@gmail.com
